Repository survev/survev, pull requests merged in 2025-08, with the labels that each got.

#239 Feat: Tests with vitest
  .github/workflows/ci.yml
  client/public/img/ui/crosshair.svg
  client/public/img/ui/expand.svg
  pnpm-lock.yaml
  pnpm-workspace.yaml
  server/src/game/map.ts
  shared/defs/mapObjectDefs.ts
  shared/defs/maps/baseDefs.ts
  shared/defs/maps/halloweenDefs.ts
  shared/defs/types/building.ts
  shared/utils/mapHelpers.ts
  shared/utils/util.ts
  tests/package.json
  tests/src/gameObjects.test.ts
  tests/src/mapObjects.test.ts
  tests/src/maps.test.ts
  tests/src/net.test.ts
  tests/src/svgs.test.ts
  tests/src/testHelpers.ts
  tests/tsconfig.json
Labels: feature

#247 More accurate reload delays
  server/src/game/gameModeManager.ts
  server/src/game/group.ts
  server/src/game/objects/player.ts
  server/src/game/team.ts
  server/src/game/weaponManager.ts
Labels: bug

#241 minor QOL tweaks
  client/public/img/loot/loot-perk-ap-rounds.svg
  client/public/img/loot/loot-perk-assume-leadership.svg
  client/src/en.json
  server/src/game/game.ts
  server/src/game/objects/player.ts
  shared/defs/gameObjects/roleDefs.ts
  shared/defs/mapObjectDefs.ts
  shared/defs/maps/desertDefs.ts
  shared/defs/maps/factionDefs.ts
  shared/defs/maps/halloweenDefs.ts
  shared/defs/maps/mainSummerDefs.ts
Labels: feature

#254 fix: preloaded guns deleting ammo
  server/src/game/objects/player.ts
Labels: bug

#250 Refactor: team and group code
  server/src/game/game.ts
  server/src/game/gameModeManager.ts
  server/src/game/group.ts
  server/src/game/map.ts
  server/src/game/objects/building.ts
  server/src/game/objects/bullet.ts
  server/src/game/objects/gameObject.ts
  server/src/game/objects/player.ts
  server/src/game/team.ts
  server/src/game/weaponManager.ts
  shared/defs/mapDefs.ts
  shared/defs/maps/testDefs.ts
  tests/src/gameTestHelpers.ts
  tests/src/reviving.test.ts
Labels: refactor
